# Generated by Django 4.1.6 on 2023-02-19 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('num_of_trips', models.IntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('average_rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('contact_num', models.BigIntegerField(primary_key=True, serialize=False)),
                ('travelagency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelagency.travelagency')),
            ],
        ),
    ]
