# Generated by Django 4.1.6 on 2023-02-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.ManyToManyField(default=['EN'], to='user.language'),
        ),
    ]
