# Generated by Django 4.1.6 on 2023-02-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_tourist_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('TR', 'Tourist'), ('GD', 'Guide')], default='TR', max_length=2),
        ),
    ]
