# Generated by Django 4.1.6 on 2023-02-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('user', '0007_user_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='reviews',
            field=models.ManyToManyField(through='reviews.GuideReviews', to='user.tourist'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='reviews',
            field=models.ManyToManyField(through='reviews.TouristReviews', to='user.guide'),
        ),
    ]
