# Generated by Django 4.1.6 on 2023-02-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0006_remove_trail_guides'),
        ('user', '0008_guide_reviews_tourist_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='trails',
            field=models.ManyToManyField(through='hire.GuideTrail', to='hire.trail'),
        ),
    ]
