# Generated by Django 4.1.6 on 2023-02-20 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.FloatField()),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.guide')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tourist')),
            ],
        ),
        migrations.CreateModel(
            name='GuideReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.FloatField()),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.guide')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tourist')),
            ],
        ),
        migrations.AddIndex(
            model_name='touristreviews',
            index=models.Index(fields=['guide', 'tourist'], name='reviews_tou_guide_i_9b8e36_idx'),
        ),
        migrations.AddConstraint(
            model_name='touristreviews',
            constraint=models.UniqueConstraint(fields=('guide', 'tourist'), name='unique_guide_tourist'),
        ),
        migrations.AddIndex(
            model_name='guidereviews',
            index=models.Index(fields=['tourist', 'guide'], name='reviews_gui_tourist_213325_idx'),
        ),
        migrations.AddConstraint(
            model_name='guidereviews',
            constraint=models.UniqueConstraint(fields=('tourist', 'guide'), name='unique_field_guide_tourist'),
        ),
    ]
