# Generated by Django 4.1.6 on 2023-02-22 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hire', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.FloatField()),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hire.trail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='trailreviews',
            index=models.Index(fields=['trail', 'user'], name='reviews_tra_trail_i_33c565_idx'),
        ),
        migrations.AddConstraint(
            model_name='trailreviews',
            constraint=models.UniqueConstraint(fields=('trail', 'user'), name='unique_field_trail_user'),
        ),
    ]
