# Generated by Django 4.1.6 on 2023-03-23 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trailreviews',
            name='unique_field_trail_user',
        ),
        migrations.RemoveIndex(
            model_name='trailreviews',
            name='reviews_tra_trail_i_33c565_idx',
        ),
    ]
