# Generated by Django 4.1.6 on 2023-02-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_trailreviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailreviews',
            name='days',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='trailreviews',
            name='difficulty',
            field=models.IntegerField(default=8),
        ),
    ]
