# Generated by Django 4.1.6 on 2023-03-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='guidereviews',
            name='unique_field_guide_tourist',
        ),
        migrations.RemoveConstraint(
            model_name='touristreviews',
            name='unique_guide_tourist',
        ),
        migrations.RemoveConstraint(
            model_name='trailreviews',
            name='unique_field_trail_user',
        ),
        migrations.RemoveIndex(
            model_name='guidereviews',
            name='reviews_gui_tourist_213325_idx',
        ),
        migrations.RemoveIndex(
            model_name='touristreviews',
            name='reviews_tou_guide_i_9b8e36_idx',
        ),
        migrations.RemoveIndex(
            model_name='trailreviews',
            name='reviews_tra_trail_i_33c565_idx',
        ),
        migrations.AlterField(
            model_name='trailreviews',
            name='difficulty',
            field=models.IntegerField(default=7),
        ),
    ]
