# Generated by Django 4.1.6 on 2023-02-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_trailreviews_days_trailreviews_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailreviews',
            name='days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trailreviews',
            name='difficulty',
            field=models.IntegerField(),
        ),
    ]
