# Generated by Django 4.1.6 on 2023-03-23 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_trailreviews_unique_field_trail_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='guidereviews',
            name='unique_field_guide_tourist',
        ),
        migrations.RemoveConstraint(
            model_name='touristreviews',
            name='unique_guide_tourist',
        ),
        migrations.RemoveIndex(
            model_name='guidereviews',
            name='reviews_gui_tourist_213325_idx',
        ),
        migrations.RemoveIndex(
            model_name='touristreviews',
            name='reviews_tou_guide_i_9b8e36_idx',
        ),
    ]
