# Generated by Django 4.1.6 on 2023-02-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to='trailphotos/')),
                ('average_days', models.IntegerField()),
                ('average_difficulty', models.IntegerField()),
                ('average_rating', models.IntegerField()),
            ],
        ),
    ]
