# Generated by Django 4.1.6 on 2023-02-24 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        ('hire', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='reviews',
            field=models.ManyToManyField(through='reviews.TrailReviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hire',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.guide'),
        ),
        migrations.AddField(
            model_name='hire',
            name='tourist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tourist'),
        ),
        migrations.AddField(
            model_name='hire',
            name='trail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hire.trail'),
        ),
        migrations.AddField(
            model_name='guidetrail',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.guide'),
        ),
        migrations.AddField(
            model_name='guidetrail',
            name='trail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hire.trail'),
        ),
        migrations.AddIndex(
            model_name='guidetrail',
            index=models.Index(fields=['guide', 'trail'], name='hire_guidet_guide_i_305660_idx'),
        ),
        migrations.AddConstraint(
            model_name='guidetrail',
            constraint=models.UniqueConstraint(fields=('guide', 'trail'), name='unique_field_guide_trail'),
        ),
    ]
