# Generated by Django 4.1.6 on 2023-02-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='average_rating',
            field=models.FloatField(),
        ),
    ]
