# Generated by Django 4.1.6 on 2023-02-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0002_alter_trail_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='average_days',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='average_difficulty',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='average_rating',
        ),
    ]
