# Generated by Django 4.1.6 on 2023-02-22 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_guide_reviews_tourist_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0004_alter_trailreviews_days_and_more'),
        ('hire', '0004_hire_guidetrail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='guides',
            field=models.ManyToManyField(through='hire.GuideTrail', to='user.guide'),
        ),
        migrations.AddField(
            model_name='trail',
            name='reviews',
            field=models.ManyToManyField(through='reviews.TrailReviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
