# Generated by Django 4.1.6 on 2023-02-23 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0005_trail_guides_trail_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='guides',
        ),
    ]
