# Generated by Django 4.1.6 on 2023-02-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0006_remove_trail_guides'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='days',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
    ]
